Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "deb-buster64-mongodb-42-vbox"
  config.vm.network "private_network", ip: "192.168.10.200"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "deb-buster64-mongodb-42-vbox"
  end
  config.vm.provision "file", source: "./mongod.conf", destination: "/tmp/mongod.conf"
  config.vm.provision "file", source: "./add_mongo_admin.js", destination: "/tmp/add_mongo_admin.js"
  config.vm.provision "shell", path: "./install_mongodb-4.2.sh"
end
